spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webapp
            client-secret: supersecret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/myrealm


server:
  port: 8081